using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using CBHBusiness;
using Client = CBHBusiness.ClientModels;

namespace CBHWA.Mappings
{
    public class qfrmInvoiceMaintenanceMapping { 
        public Client.qfrmInvoiceMaintenance MapModels(qfrmInvoiceMaintenance model)
        {
            var data = new Client.qfrmInvoiceMaintenance
            {
                InvoiceKey = model.InvoiceKey,
                InvoiceJobKey = model.InvoiceJobKey,
                InvoicePrefix = model.InvoicePrefix,
                InvoiceNum = model.InvoiceNum,
                InvoiceRevisionNum = model.InvoiceRevisionNum,
                InvoiceDate = model.InvoiceDate,
                InvoiceRecipient = model.InvoiceRecipient,
                InvoiceVendorKey = model.InvoiceVendorKey,
                InvoiceVendorContactKey = model.InvoiceVendorContactKey,
                InvoiceCustKey = model.InvoiceCustKey,
                InvoiceCustContactKey = model.InvoiceCustContactKey,
                InvoiceBillingName = model.InvoiceBillingName,
                InvoiceBillingAddress1 = model.InvoiceBillingAddress1,
                InvoiceBillingAddress2 = model.InvoiceBillingAddress2,
                InvoiceBillingCity = model.InvoiceBillingCity,
                InvoiceBillingState = model.InvoiceBillingState,
                InvoiceBillingZip = model.InvoiceBillingZip,
                InvoiceBillingCountryKey = model.InvoiceBillingCountryKey,
                InvoiceCustShipKey = model.InvoiceCustShipKey,
                InvoiceCustReference = model.InvoiceCustReference,
                InvoiceEmployeeKey = model.InvoiceEmployeeKey,
                InvoiceCurrencyCode = model.InvoiceCurrencyCode,
                InvoiceCurrencyRate = model.InvoiceCurrencyRate,
                InvoicePaymentTerms = model.InvoicePaymentTerms,
                InvoiceMemo = model.InvoiceMemo,
                InvoiceModifiedBy = model.InvoiceModifiedBy,
                InvoiceModifiedDate = model.InvoiceModifiedDate,
                InvoiceCreatedBy = model.InvoiceCreatedBy,
                InvoiceCreatedDate = model.InvoiceCreatedDate,
                InvoiceMemoFont = model.InvoiceMemoFont,
                CustKey = model.CustKey,
                CustPeachtreeID = model.CustPeachtreeID,
                CustPeachtreeIndex = model.CustPeachtreeIndex,
                CustName = model.CustName,
                CustAddress1 = model.CustAddress1,
                CustAddress2 = model.CustAddress2,
                CustCity = model.CustCity,
                CustState = model.CustState,
                CustZip = model.CustZip,
                CustCountryKey = model.CustCountryKey,
                CustPhone = model.CustPhone,
                CustFax = model.CustFax,
                CustEmail = model.CustEmail,
                CustWebsite = model.CustWebsite,
                CustSalesRepKey = model.CustSalesRepKey,
                CustOrdersRepKey = model.CustOrdersRepKey,
                CustLanguageCode = model.CustLanguageCode,
                CustStatus = model.CustStatus,
                CustModifiedBy = model.CustModifiedBy,
                CustModifiedDate = model.CustModifiedDate,
                CustCreatedBy = model.CustCreatedBy,
                CustCreatedDate = model.CustCreatedDate,
                CustCreditLimit = model.CustCreditLimit,
                CustCurrencyCode = model.CustCurrencyCode,
                CustMemo = model.CustMemo,
                VendorKey = model.VendorKey,
                VendorName = model.VendorName,
                VendorPeachtreeID = model.VendorPeachtreeID,
                VendorPeachtreeItemID = model.VendorPeachtreeItemID,
                VendorPeachtreeJobID = model.VendorPeachtreeJobID,
                VendorDisplayToCust = model.VendorDisplayToCust,
                VendorContact = model.VendorContact,
                VendorAddress1 = model.VendorAddress1,
                VendorAddress2 = model.VendorAddress2,
                VendorCity = model.VendorCity,
                VendorState = model.VendorState,
                VendorZip = model.VendorZip,
                VendorCountryKey = model.VendorCountryKey,
                VendorPhone = model.VendorPhone,
                VendorFax = model.VendorFax,
                VendorEmail = model.VendorEmail,
                VendorWebsite = model.VendorWebsite,
                VendorLanguageCode = model.VendorLanguageCode,
                VendorAcctNum = model.VendorAcctNum,
                VendorCarrier = model.VendorCarrier,
                VendorModifiedBy = model.VendorModifiedBy,
                VendorModifiedDate = model.VendorModifiedDate,
                VendorCreatedBy = model.VendorCreatedBy,
                VendorCreatedDate = model.VendorCreatedDate,
                VendorDefaultCommissionPercent = model.VendorDefaultCommissionPercent,
                JobShipType = model.JobShipType,
                JobShipDate = model.JobShipDate,
                FullInvoiceNum = model.FullInvoiceNum
            };

            return data;
        }

        public qfrmInvoiceMaintenance MapModels(Client.qfrmInvoiceMaintenance model)
        {
            var data = new qfrmInvoiceMaintenance
            {
                InvoiceKey = model.InvoiceKey,
                InvoiceJobKey = model.InvoiceJobKey,
                InvoicePrefix = model.InvoicePrefix,
                InvoiceNum = model.InvoiceNum,
                InvoiceRevisionNum = model.InvoiceRevisionNum,
                InvoiceDate = model.InvoiceDate,
                InvoiceRecipient = model.InvoiceRecipient,
                InvoiceVendorKey = model.InvoiceVendorKey,
                InvoiceVendorContactKey = model.InvoiceVendorContactKey,
                InvoiceCustKey = model.InvoiceCustKey,
                InvoiceCustContactKey = model.InvoiceCustContactKey,
                InvoiceBillingName = model.InvoiceBillingName,
                InvoiceBillingAddress1 = model.InvoiceBillingAddress1,
                InvoiceBillingAddress2 = model.InvoiceBillingAddress2,
                InvoiceBillingCity = model.InvoiceBillingCity,
                InvoiceBillingState = model.InvoiceBillingState,
                InvoiceBillingZip = model.InvoiceBillingZip,
                InvoiceBillingCountryKey = model.InvoiceBillingCountryKey,
                InvoiceCustShipKey = model.InvoiceCustShipKey,
                InvoiceCustReference = model.InvoiceCustReference,
                InvoiceEmployeeKey = model.InvoiceEmployeeKey,
                InvoiceCurrencyCode = model.InvoiceCurrencyCode,
                InvoiceCurrencyRate = model.InvoiceCurrencyRate,
                InvoicePaymentTerms = model.InvoicePaymentTerms,
                InvoiceMemo = model.InvoiceMemo,
                InvoiceModifiedBy = model.InvoiceModifiedBy,
                InvoiceModifiedDate = model.InvoiceModifiedDate,
                InvoiceCreatedBy = model.InvoiceCreatedBy,
                InvoiceCreatedDate = model.InvoiceCreatedDate,
                InvoiceMemoFont = model.InvoiceMemoFont,
                CustKey = model.CustKey,
                CustPeachtreeID = model.CustPeachtreeID,
                CustPeachtreeIndex = model.CustPeachtreeIndex,
                CustName = model.CustName,
                CustAddress1 = model.CustAddress1,
                CustAddress2 = model.CustAddress2,
                CustCity = model.CustCity,
                CustState = model.CustState,
                CustZip = model.CustZip,
                CustCountryKey = model.CustCountryKey,
                CustPhone = model.CustPhone,
                CustFax = model.CustFax,
                CustEmail = model.CustEmail,
                CustWebsite = model.CustWebsite,
                CustSalesRepKey = model.CustSalesRepKey,
                CustOrdersRepKey = model.CustOrdersRepKey,
                CustLanguageCode = model.CustLanguageCode,
                CustStatus = model.CustStatus,
                CustModifiedBy = model.CustModifiedBy,
                CustModifiedDate = model.CustModifiedDate,
                CustCreatedBy = model.CustCreatedBy,
                CustCreatedDate = model.CustCreatedDate,
                CustCreditLimit = model.CustCreditLimit,
                CustCurrencyCode = model.CustCurrencyCode,
                CustMemo = model.CustMemo,
                VendorKey = model.VendorKey,
                VendorName = model.VendorName,
                VendorPeachtreeID = model.VendorPeachtreeID,
                VendorPeachtreeItemID = model.VendorPeachtreeItemID,
                VendorPeachtreeJobID = model.VendorPeachtreeJobID,
                VendorDisplayToCust = model.VendorDisplayToCust,
                VendorContact = model.VendorContact,
                VendorAddress1 = model.VendorAddress1,
                VendorAddress2 = model.VendorAddress2,
                VendorCity = model.VendorCity,
                VendorState = model.VendorState,
                VendorZip = model.VendorZip,
                VendorCountryKey = model.VendorCountryKey,
                VendorPhone = model.VendorPhone,
                VendorFax = model.VendorFax,
                VendorEmail = model.VendorEmail,
                VendorWebsite = model.VendorWebsite,
                VendorLanguageCode = model.VendorLanguageCode,
                VendorAcctNum = model.VendorAcctNum,
                VendorCarrier = model.VendorCarrier,
                VendorModifiedBy = model.VendorModifiedBy,
                VendorModifiedDate = model.VendorModifiedDate,
                VendorCreatedBy = model.VendorCreatedBy,
                VendorCreatedDate = model.VendorCreatedDate,
                VendorDefaultCommissionPercent = model.VendorDefaultCommissionPercent,
                JobShipType = model.JobShipType,
                JobShipDate = model.JobShipDate,
                FullInvoiceNum = model.FullInvoiceNum
            };

            return data;
        }
    }
}